export const limiters = [
  { name: 'NE', reg: /^NE/ },
  { name: 'EQ', reg: /^EQ/ },
  { name: 'LT', reg: /^LT/ },
  { name: 'LE', reg: /^LE/ },
  { name: 'GT', reg: /^GT/ },
  { name: 'GE', reg: /^GE/ },
  { name: '{', reg: /^{/ },
  { name: '}', reg: /^}/ },
  { name: ',', reg: /^,/ },
  { name: ':=', reg: /^:=/ },
  { name: ':', reg: /^:/ },
  { name: '(', reg: /^\(/ },
  { name: ')', reg: /^\)/ },
  { name: '+', reg: /^\++/ },
  { name: '-', reg: /^--/ },
  { name: ';', reg: /^;/ },
  { name: '.', reg: /^\.\.\./ },
  { name: '~', reg: /^~/ },
  { name: 'plus', reg: /^plus/ },
  { name: 'min', reg: /^min/ },
  { name: 'or', reg: /^or/ },
  { name: 'mult', reg: /^mult/ },
  { name: 'div', reg: /^div/ },
  { name: 'and', reg: /^and/ },
];
