export const limiters = [
  { name: 'NE', reg: /^NE(?=[^\w])/ },
  { name: 'EQ', reg: /^EQ(?=[^\w])/ },
  { name: 'LT', reg: /^LT(?=[^\w])/ },
  { name: 'LE', reg: /^LE(?=[^\w])/ },
  { name: 'GT', reg: /^GT(?=[^\w])/ },
  { name: 'GE', reg: /^GE(?=[^\w])/ },
  { name: '{', reg: /^{/ },
  { name: '}', reg: /^}/ },
  { name: ',', reg: /^,/ },
  { name: ':=', reg: /^:=/ },
  { name: ':', reg: /^:/ },
  { name: '(', reg: /^\(/ },
  { name: ')', reg: /^\)/ },
  { name: '+', reg: /^\++/ },
  { name: '-', reg: /^--/ },
  { name: ';', reg: /^;/ },
  { name: '.', reg: /^\.\.\./ },
  { name: '~', reg: /^~/ },
  { name: 'plus', reg: /^plus(?=[^\w])/ },
  { name: 'min', reg: /^min(?=[^\w])/ },
  { name: 'or', reg: /^or(?=[^\w])/ },
  { name: 'mult', reg: /^mult(?=[^\w])/ },
  { name: 'div', reg: /^div(?=[^\w])/ },
  { name: 'and', reg: /^and(?=[^\w])/ },
];
