export const limiters = [
  { id: 0, name: 'NE', reg: /^NE/ },
  { id: 1, name: 'EQ', reg: /^EQ/ },
  { id: 2, name: 'LT', reg: /^LT/ },
  { id: 3, name: 'LE', reg: /^LE/ },
  { id: 4, name: 'GT', reg: /^GT/ },
  { id: 5, name: 'GE', reg: /^GE/ },
  { id: 6, name: '{', reg: /^{/ },
  { id: 7, name: '}', reg: /^}/ },
  { id: 8, name: ',', reg: /^,/ },
  { id: 9, name: ':=', reg: /^:=/ },
  { id: 10, name: ':', reg: /^:/ },
  { id: 11, name: '(', reg: /^\(/ },
  { id: 12, name: ')', reg: /^\)/ },
  { id: 13, name: '+', reg: /^\+/ },
  { id: 14, name: '-', reg: /^-/ },
  { id: 15, name: ';', reg: /^;/ },
  { id: 16, name: '.', reg: /^\./ },
  { id: 17, name: '~', reg: /^~/ },
  { id: 18, name: 'plus', reg: /^plus/ },
  { id: 19, name: 'min', reg: /^min/ },
  { id: 20, name: 'or', reg: /^or/ },
  { id: 21, name: 'mult', reg: /^mult/ },
  { id: 22, name: 'div', reg: /^div/ },
  { id: 23, name: 'and', reg: /^and/ },
];
