export const words = [
  { name: 'true', reg: /^true(?=[^\w])/ },
  { name: 'false', reg: /^false(?=[^\w])/ },
  { name: 'int', reg: /^int(?=[^\w])/ },
  { name: 'float', reg: /^float(?=[^\w])/ },
  { name: 'bool', reg: /^bool(?=[^\w])/ },
  { name: 'begin', reg: /^begin(?=[^\w])/ },
  { name: 'end', reg: /^end(?=[^\w])/ },
  { name: 'if', reg: /^if(?=[^\w])/ },
  { name: 'else', reg: /^else(?=[^\w])/ },
  { name: 'for', reg: /^for(?=[^\w])/ },
  { name: 'to', reg: /^to(?=[^\w])/ },
  { name: 'step', reg: /^step(?=[^\w])/ },
  { name: 'next', reg: /^next(?=[^\w])/ },
  { name: 'while', reg: /^while(?=[^\w])/ },
  { name: 'readln', reg: /^readln(?=[^\w])/ },
  { name: 'writeln', reg: /^writeln(?=[^\w])/ },
];
