export const words = [
  { name: 'true', reg: /^true/ },
  { name: 'false', reg: /^false/ },
  { name: 'int', reg: /^int/ },
  { name: 'float', reg: /^float/ },
  { name: 'bool', reg: /^bool/ },
  { name: 'begin', reg: /^begin/ },
  { name: 'end', reg: /^end/ },
  { name: 'if', reg: /^if/ },
  { name: 'else', reg: /^else/ },
  { name: 'for', reg: /^for/ },
  { name: 'to', reg: /^to/ },
  { name: 'step', reg: /^step/ },
  { name: 'next', reg: /^next/ },
  { name: 'while', reg: /^while/ },
  { name: 'readln', reg: /^readln/ },
  { name: 'writeln', reg: /^writeln/ },
  { name: 'step', reg: /^step/ },
];
